# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='')),
                ('power', models.PositiveIntegerField()),
                ('volume', models.FloatField()),
                ('number_of_cylinders', models.PositiveIntegerField()),
            ],
        ),
    ]
