# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import engines.models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0002_engine_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engine',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='engine',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=engines.models.upload_location, width_field='width_field'),
        ),
    ]
