# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import engines.models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0003_auto_20161203_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='engine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=engines.models.upload_location),
        ),
    ]
