# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20161204_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='buyer_last_name',
            field=models.CharField(default='no information', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='buyer_name',
            field=models.CharField(default='no information', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='addition_equipment',
            field=models.ManyToManyField(blank=True, to='equipments.AdditionEquipment'),
        ),
    ]
