# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_models', '0003_auto_20161203_1419'),
        ('factories', '0001_initial'),
        ('autoshops', '0003_auto_20161128_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_engine', models.CharField(max_length=20, unique=True)),
                ('no_cab', models.CharField(max_length=20, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('release_field', models.DateField()),
                ('autoshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoshops.Autoshop')),
            ],
        ),
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_color', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_state', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.CarColor'),
        ),
        migrations.AddField(
            model_name='car',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factories.Factory'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_models.CarModel'),
        ),
        migrations.AddField(
            model_name='car',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.CarState'),
        ),
    ]
