# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 21:58
from __future__ import unicode_literals

import autoshops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoshop',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=autoshops.models.upload_location, width_field='width_field'),
        ),
    ]
