# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshops', '0002_autoshop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoshop',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autoshop',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
