# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoshops', '0003_auto_20161128_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoshop',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='autoshop',
            name='width_field',
        ),
    ]
