# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engines', '0002_engine_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_type', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
                ('volume_fuel', models.FloatField()),
                ('consumption_fuel', models.FloatField()),
                ('number_of_places', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('max_weight', models.PositiveIntegerField()),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_models.Cab')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engines.Engine')),
            ],
        ),
    ]
