# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20161203_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
